# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ClickWiki
email: hello@clickwiki.net
description: >- # this means to ignore newlines until "baseurl:"
  A community-driven wiki-based website to archive and
  inform of all things Clickteam, Multimedia Fusion and their
  products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clickwiki.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ClickWiki
github_username:  ClickWiki
accent_colour: "#0084EB"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Social Links
facebook_url: "https://facebook.com/ClickWiki"
twitter_url: "https://twitter.com/ClickWiki"
github_url: "https://github.com/ClickWiki"
discord_url: "https://discord.gg/42jVPPd"

# Project Links
repo_url: "https://github.com/ClickWiki/clickwiki.net"
issues_url: "https://github.com/ClickWiki/clickwiki.net/issues"
pr_url: "https://github.com/ClickWiki/clickwiki.net/pulls"
watchers_url: "https://github.com/ClickWiki/clickwiki.net/watchers"
stars_url: "https://github.com/ClickWiki/clickwiki.net/stargazers"
forks_url: "https://github.com/ClickWiki/clickwiki.net/network"
contributors_url: "https://github.com/ClickWiki/clickwiki.net/graphs/contributors"

# Categories (for breadcrumbs)
breadcrumbs:
    - id: exporters
      title: "Exporters"
      url: "/exporters/"

    - id: clickteam
      title: "Clickteam"
      url: "/clickteam/"

    - id: extensions
      title: "Extensions"
      url: "/extensions/"

    - id: fusion
      title: "Fusion"
      url: "/fusion/"

    - id: tools
      title: "Tools"
      url: "/tools/"

    - id: file-extensions
      title: "File Extensions"
      url: "/file-extensions/"


# Header items
navigation_categories:
    - heading: "All About Clickteam"

    - label: "Clickteam"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/Clickteam Logo.png"
      url: "/clickteam/"

    - label: "Products"
      icon_type: "fa"
      icon: "fa-shopping-bag"
      url: "/products/"

    - heading: "Fusion"

    - label: "Exporters"
      icon_type: "fa"
      icon: "fa-download"
      url: "/exporters/"

    - label: "Extensions"
      icon_type: "fa"
      icon: "fa-puzzle-piece"
      url: "/extensions/"

    - label: "Best Practices"
      icon_type: "fa"
      icon: "fa-question-circle"
      url: "/best-practices/"

    - label: "Interface"
      icon_type: "fa"
      icon: "fa-mouse-pointer"
      url: "/interface/"

    - label: "File Extensions"
      icon_type: "fa"
      icon: "fa-file"
      url: "/file-extensions/"

    - heading: "Community"

    - label: "Resources"
      icon_type: "fa"
      icon: "fa-folder"
      url: "/resources/"

    - label: "User Creations"
      icon: "/wiki/assets/Clickteam/Fused Logo.png"
      url: "/made-with-fusion/"


navigation_external_links:
    - label: "Clickteam.com"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/Clickteam Logo.png"
      url: "https://www.clickteam.com"

    - label: "Clickteam Community"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/Clickteam Logo.png"
      url: "https://community.clickteam.com"

    - label: "Community Passport"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/Clickteam Logo.png"
      url: "https://community.clickteam.com/passport"

    - label: "Clickteam Shop"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/Shop.png"
      url: "https://www.clickteam.com/web-shop"

    - label: "Clickteam Library"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/Clickteam_Library.png"
      url: "http://library.clickteam.com/"

    - label: "ClickStore"
      icon_type: "img"
      icon: "/wiki/assets/Clickteam/ClickStore.png"
      url: "http://clickstore.clickteam.com/"

    - label: "Bug Tracker"
      icon_type: "img"
      icon: "/wiki/assets/CC-BY-4.0/BugBox.png"
      url: "http://bugbox.clickteam.com/"
